FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build


FROM nginx
WORKDIR  /usr/share/nginx/html
# COPY custom.conf /etc/nginx/conf.d/custom.conf
RUN rm -rf ./*
COPY --from=build /app/build .
